services:
  webapp:
    build: .
    container_name: tesco_tracker_web
    restart: unless-stopped
    command: python app.py
    volumes:
      - ${DATA_FOLDER}:/app/data
    ports:
      - "50001:50001"
    env_file:
      - .env
    environment:
      - TZ=Europe/Budapest

  scheduler:
    build: .
    container_name: tesco_tracker_scheduler
    restart: unless-stopped
    command: python scheduler.py
    volumes:
      - ${DATA_FOLDER}:/app/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Budapest
